### ISSUE TITLE
Support page action method dispatching based on form field

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/RazorPages#12]
Would be nice to be able to have something like the following, where a specially named form field would effect which post handler was invoked by adding a suffix to look for. This avoids the need to take in multiple parameters for the sake of binding into a single action even if they aren't all used for each action type.

``` c#
public async Task<IActionResult> OnPost(Customer customer)
{
    // Create the customer
    ...
}

public async Task<IActionResult> OnPostDelete(int id)
{
    // Delete the customer
    ...
}
```
``` html
<form method="post">
    @Customer.Id - @Customer.Name
    <input type="hidden" name="id" value="@Customer.Id" />
    <button type="submit" name="__action" value="delete">Delete</button>
</form>
<form method="post">
    <label asp-for="Name" />
    <input asp-for="Name" />
    <button type="submit">Create</button>
</form>
```

**Comment by rynowak** [comment]
We'd probably also want a TagHelper of some kind for this :grinning: 

```
<button type="submit" asp-command="delete">Delete</button>
```

**Comment by DamianEdwards** [comment]
Ooooh yes, nice!

**Comment by glennc** [comment]
+1 Wanted this last night and was coming here to ask about it :).

**Comment by hishamco** [comment]
What if we have a single form instead of two, the ```asp-command``` value in ```OnPost``` will let us know whether we need to create or delete the custom

**Comment by DamianEdwards** [comment]
@hishamco yep, that would work too.

**Comment by rynowak** [comment]
cf7e3657e4377c22367b45cf4b6f01a25b0ab807 adds support for `{formaction}` in a route. The formaction will be parsed from the portion of the handler name following the verb and preceding async.

So for `public Task<IActionResult> OnPostUpdateAsync(...) { }` - Update is the formaction.

Right now the only way this works is via route data, but we could add support for query string or form data if it makes sense. The infrastructure is in place now, so this would be easy to extend.
