### ISSUE TITLE
Get rid of code-gen for ExecuteAsync and use reflection

### ISSUE THREAD

**Issue by rynowak** [aspnet/RazorPages#15]
We want to get rid of features that require deep introspection of the user's code for code-generation, and `ExecuteAsync` is one of these. 

We'll use reflection + compiled expressions instead.

**Comment by hishamco** [comment]
@rynowak I think this fixed by https://github.com/aspnet/RazorPages/commit/d1d321209dd5423f04609a4f7d53e1de1bd87659
