### ISSUE TITLE
Customizable RazorPages location

### ISSUE THREAD

**Issue by hishamco** [aspnet/RazorPages#16]
It will be nice if we have a programatic configuration to set the RazorPages directory via simple ```Location``` property in RazorPagesOptions instead of fixed one.

/cc @DamianEdwards

**Comment by DamianEdwards** [comment]
Yeah it will definitely be configurable.

**Comment by hishamco** [comment]
Can I make a PR for such thing?!! Is ```RazorPagesOptions``` suitable place for such thing?

**Comment by DamianEdwards** [comment]
It already has a configurable list of `IFileProvider` and I don't think it's really worth the hassle for this prototype, which is largely just throw-away work. We're trying to focus on enabling things that are important to validating the page programming model and I don't think this meets that bar.
