### ISSUE TITLE
Rethinking about razor pages extension

### ISSUE THREAD

**Issue by hishamco** [aspnet/RazorPages#17]
**.razor** extension is little confusing for the devs that already worked with .cshml & .vbhtml, because we still mix CSharp or VB code with HTML, IMHO:

- Bring back **.cshtml** instead of **.razor**, rename the code behind extension to **.chtml.cs**
- Razor Pages is a new thing with new primitives and help for page focused scenarios so the **.razor** is make sense in this case, but may we need to rename the code behind extension to **.razor.cs** like what we have saw in ASP.NET WebForms, because this will indicate it's not a normal class, it's a code behind

**Comment by rynowak** [comment]
Thanks for the feedback, I'll add this to the FAQ. `.razor` is being used in the prototype specifically so that tooling won't work. We know that tooling with give spurious errors and wrong answers for pages, and don't want to wast time on that.

**Comment by hishamco** [comment]
It's not about the tooling, this feedback for naming the code-behind file

**Comment by hishamco** [comment]
After your PR https://github.com/aspnet/RazorPages/commit/ce24ebe2328ef13ccd531f3164ae5ba6b9fcf2ab I know why it's .razor not .cshtml :smile: , but still i'm not sure why is it **.cs** not **.cshtml.cs** or **.razor.cs** for the prototype purpose

/cc @DamianEdwards

**Comment by DamianEdwards** [comment]
The code-behind can be called whatever you like, as long as it ends in .cs, so .cshtml.cs will work fine. It's compiled with the project, not the page.

**Comment by hishamco** [comment]
Thanks
