### ISSUE TITLE
Generate ILogger

### ISSUE THREAD

**Issue by glennc** [aspnet/RazorPages#18]
In my branch of this I am generating a Logger, since I don't have a class for an ILogger<T>.

See: https://github.com/aspnet/RazorPages/blob/glennc/todo/src/Microsoft.AspNetCore.Mvc.RazorPages/Compilation/PageCodeGenerator.cs#L81

I am using it in the simple todo sample I was creating: https://github.com/aspnet/RazorPages/blob/glennc/todo/samples/RazorPages.Todo/SimpleTodo/Pages/Index.razor#L21

If we are good with that then I will leave this in for my PR. The alternative would be something like injecting an `ILoggerFactory` and do `loggerFactory.CreateLogger("IndexPage")`.

**Comment by glennc** [comment]
cc @DamianEdwards

**Comment by hishamco** [comment]
While we can inject the logger if we have to, we can use it explicit if it's needed. I'm still a fan of pay for the things that I need, so that's the way of how new asp.net core is built.

**Comment by glennc** [comment]
@hishamco What? Do you mean inject the logger factory and create a logger if you want it? Sure you can do that, but you can't use the generic `CreateLogger` extension method because you don't know the class name in your functions block. Right?

**Comment by hishamco** [comment]
Unfortunately we can't use the generic version of the ```CreateLogger``` method in this case

**Comment by DamianEdwards** [comment]
Fixed
