### ISSUE TITLE
Support _ViewImports

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/RazorPages#20]
I know this is just the prototype but it'd be great to get something like ViewImports.cshtml working so the page files don't have to have all the `@using` statements in them. Seems we'd need to get some hacked up form of [this](https://github.com/aspnet/Mvc/blob/659cdc336484039f4c2e619ddbf1cc4f09459523/src/Microsoft.AspNetCore.Mvc.Razor.Host/MvcRazorHost.cs#L326) from MVC working.

**Comment by hishamco** [comment]
You read my mind Damian, yesterday I was trying to use _ViewImports.cshtml with no luck, after that I realize it's not supported :smile:

**Comment by rynowak** [comment]
:disappointed:  Fiiiiiiiiiiiiiiiiiiiiiiiiiiiine

**Comment by hishamco** [comment]
What about _PageStart aka _ViewStart?

**Comment by DamianEdwards** [comment]
Yeah we'd support that as well and would be certainly nice to have in this prototype.

**Comment by rynowak** [comment]
Added `_PageImports` support. Check it out, it's dope!
