### ISSUE TITLE
Treat Url Segments as Url Data

### ISSUE THREAD

**Issue by hishamco** [aspnet/RazorPages#21]
There are many scenarios where we need to treat a part of the url as data. Assume we have

http://localhost:5000/Customer/**12**
http://localhost:5000/Customer/**Delete**/**12**

It is handy to have a property such as ```UrlData``` that holds the Url segments (except the page name)

**Comment by DamianEdwards** [comment]
We definitely need/want to support these types of URLs with route data, but we'll just `RouteData` for it, not a new concept.

@rynowak are we able to enable something like this in the prototype? What's the easiest way we could do that? Implement `route.MapPageRoute("Customer/{?id:int}", "Customer.razor")` or similar?

**Comment by rynowak** [comment]
Pages use attribute routing currently. We could swap that to use conventional routing - or we could enable application model + conventions. I actually (gasp) lean towards conventional routing for this.

**Comment by DamianEdwards** [comment]
Yeah, until we support `@page "Customers/{id:int?}"` it seems conventional routes are a better approach here.

**Comment by davidfowl** [comment]
+1, UrlData doesn't seem like the best approach (yes it's simple but you really want to avoid the parsing and validation in the page itself).

**Comment by hishamco** [comment]
What I mean is a way to access such data :) not necessary ```UrlData``` which we have seen in ASP.NET WebPages

**Comment by DamianEdwards** [comment]
@hishamco you'll be able to access it via `RouteData` and/or have it bind directly to page action parameters. Or am I misunderstanding you?

**Comment by hishamco** [comment]
Bind them to the page parameters make it simple to access them in both ```OnGetAsync``` and ```OnPostAsync```

**Comment by rynowak** [comment]
This is done now, pages can have custom routes

**Comment by hishamco** [comment]
Yep, thanks
