### ISSUE TITLE
Consider syntax for filters

### ISSUE THREAD

**Issue by rynowak** [aspnet/RazorPages#22]
Well. It happened. I ran into a case where I wanted to configure authz filters for a page.

It would be easy to put attributes on a code-behind and have that just work. But that doesn't seem wholly aligned with the principle of *less ceremony*

Thoughts on something like an `attributes { }` directive?

This is in the spirit of what we're doing with other things in RazorPages.

```
@page
@attributes {
    [AllowAnonymous]
}

....
```

**Comment by DamianEdwards** [comment]
Would enable attribute routes to be done there too, could drop the need for the `[]` if we wanted too, just project them into it directly:
````
@attributes {
    AllowAnonymous, Route("MyUrl/{id:int?}")
}
```

**Comment by rynowak** [comment]
Putting routing information there implies that we'd compile code to build the list of routes, maybe I don't like this idea yet.. hmm

**Comment by DamianEdwards** [comment]
Oh yeah good point. This could be a Pandora's Box we don't want to open just yet.

**Comment by rynowak** [comment]
I'm still convinced that we can build routing with `@page foo/bar` and have the performance be OK. Maybe I'll do that after the host part so we can prove it out.

**Comment by DamianEdwards** [comment]
Cool, looking forward to seeing that.

**Comment by hishamco** [comment]
What if we decorate ```OnGetAsync``` and ```OnPostAsync``` methods with ```AllowAnonymous``` or ```Authorize``` attributes without introducing a new directive such as:
```csharp
[AllowAnonymous]
public Task OnGetAsync()
{
}

[Authorize]
public Task OnPostAsync()
{
}
```
It's clean and simple

**Comment by hishamco** [comment]
Also we can decorate the page code-behind class with authorization attributes for filter the entire page. IMHO let us make things clean and simple without introducing extra new stuff, this we make the shift much much easier because MVC is already use such attributes in the controllers

**Comment by DamianEdwards** [comment]
Yep, @rynowak and I basically came to the same conclusion today when we spoke about it.

**Comment by davidfowl** [comment]
👏

**Comment by rynowak** [comment]
We're going to do something much more conservative here for now. The conclusion that we came too is that there isn't a super strong need for filters in pages other than auth. Most things are application-wide policy - which just works, but auth was the exception. You need to be able to scope auth.

ebd05f5ad1c8c76f5ab4365e3ad7628adfe5634c is an implementation of auth, using filters based on conventions.

**Comment by hishamco** [comment]
Does the authorization via attributes will be support soon?

**Comment by rynowak** [comment]
It's not likely to happen ever if we can avoid it. This would become yet another thing that requires us to parse and understand codegen up front so we can understand the base class.

**Comment by hishamco** [comment]
I don't think we can able to authorize the ```OnPost``` or ```OnPostAsync``` and allow ```OnGet``` or ```OnGetAsync``` in this approach
