### ISSUE TITLE
Do we really need "Views" folder anymore?!!

### ISSUE THREAD

**Issue by hishamco** [aspnet/RazorPages#26]
As we know Razor Pages are mainly for page-focused scenarios, while all the razor pages should be in Pages folder (for now) is there a need for the views folder anymore?!! some may said it's for layouts, partials .. etc, but If we looked to the ASP.NET Web Pages all the .cshtml or .vbhtml should be in the root even the layout pages. Still I have something in my mind because we are not using MVC pattern in this programming model

**Comment by hishamco** [comment]
After adding ```_PageImports.razor``` in the commit https://github.com/aspnet/RazorPages/commit/48410c4fdcb4b7067a0a9bc21e492f766c339219 and soon ```_PageStart.razor```, moving the ```_Layout.razor``` aka ```_Layout.cshtml``` to Pages folder will be good choice for consistency

**Comment by DamianEdwards** [comment]
It's not needed, you can just move it wherever you like right now and set it appropriately. What **doesn't** work is setting it based on relative path, that would be nice, but not something for this prototype.

**Comment by hishamco** [comment]
But what can we do in the scenario that explained in #31 if we remove it?!!

**Comment by DamianEdwards** [comment]
This is just a prototype and as such we're not going to make everything work. We have to use our imagination for some parts until we build the real thing :smile:

**Comment by hishamco** [comment]
I agree with you, but I post the above issue from a real website problem, anyhow I will use _ViewImports instead to solve the issue
