### ISSUE TITLE
Partial's TagHelpers don't work with @addTagHelper declaration in _PageImports

### ISSUE THREAD

**Issue by hishamco** [aspnet/RazorPages#31]
Today I faced a strange issue with **Partials** in [my repo](https://github.com/hishamco/ThisDevelopersLife), I have a tag helper in side one of my partials which is used in one of the razor pages, I declared the ```@addTagHelper *, ThisDevelopersLife``` inside the ```_PageImports.razor```, but the tag helper doesn't work as expected unless I moved that line to the partial itself.
My expectation that all the imports will flow from ```_PageImports.razor``` to the razor pages to the partials

/cc @NTaylorMullen

**Comment by rynowak** [comment]
In the prototype `_PageImports` and `_ViewImports` are separate worlds.

This is not something we are going to fix in the prototype, I'd suggest just using `_ViewImports`.

**Comment by hishamco** [comment]
What's the different between them?

**Comment by hishamco** [comment]
Thanks for your clarification, but why we need sort of view instead of a page?!!
