### ISSUE TITLE
A getting started guide

### ISSUE THREAD

**Issue by TKharaishvili** [aspnet/RazorPages#37]
A "getting started" guide for VS and VS Code would be great.

P.S. I hope this is the appropriate place for this kind of a request...

**Comment by rynowak** [comment]
I had started doing something here, https://github.com/aspnet/RazorPages/wiki#getting-started but I think it needs to be expanded

**Comment by Eilon** [comment]
Everything that matters in this repo has moved to https://github.com/aspnet/Mvc/, so closing this issue.
