### ISSUE TITLE
Is there a need for AllowAnonymousToPage and AllowAnonymousToFolder?

### ISSUE THREAD

**Issue by hishamco** [aspnet/RazorPages#40]
Since the default behavior is to allow the anonymous users to access the pages and folders unless we used ```AuthorizePage``` or ```AuthorizeFolder```., so I'm not sure if there's a to add such APIs in the system

**Comment by rynowak** [comment]
> unless we used AuthorizePage or AuthorizeFolder

This is why it's needed. 

Imagine you require auth everwhere but the 'login' page. So you globally apply auth and then allow anonymous to just the login page.
