### ISSUE TITLE
Adding AuthorizePage & AuthorizeFolder without requiring a policy

### ISSUE THREAD

**Issue by hishamco** [aspnet/RazorPages#45]
@rynowak It will be nice if we have an overload to authorize a page or a folder without requiring a policy to be supplied, perhaps I wanna use a simple cookie authentication that will handle the authentication process.
This is an equivalent to using `AuthorizeAttribute` in MVC controller or an action

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#5936
