### ISSUE TITLE
Make the page class initialize ViewDataDictionary<T> to generated page type if @model isn't specified

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/RazorPages#5]
If `@model` isn't specified explicitly, a `ViewDataDictionary<T>` should be generated on the page where `T` is the generated page class. This allows things like the form Tag Helpers to work on properties declared directly on the page.

Same goes for `IHtmlHelper<T>` too.

**Comment by hishamco** [comment]
This is confused little bit, semantically if the ```@model``` not specified explicitly it should be ```null``` instead of the page itself unless there're some scenarios when this is useful

**Comment by DamianEdwards** [comment]
Yeah the real desire here is to just allow `ViewDataDictionary<T>` to work by default, and that doesn't require there to be a `Model` property, just that the generated page class is used as the `T` if `@model` isn't specified.

**Comment by dougbu** [comment]
@DamianEdwards this sounds like it could mean a few things. Which do you mean?

1. Initialize the `ViewDataDictionary` with the page as the `Model`. (This automatically updates both `Model` and `ModelMetadata` today.)
2. Create an instance of `ViewDataDictionary<TPage>` and initialize that as in 1.
3. Type the injected property as `ViewDataDictionary<TPage>` and create value as in 2.

----

Without making any of the above changes, users can write `model => Property` when using HTML helpers or `attribute="@Property"` when using tag helpers.

The first is a behaviour change from other views lacking `@model`. In particular, users can still set `ViewData.Model` to something different later.

The second will make razor pages behave differently from other views lacking `@model`. Setting `ViewData.Model` to something incompatible would `throw` an `InvalidOperationException` at runtime.

The third would also make razor pages behave differently from other views lacking `@model`. Setting `ViewData.Model` to something incompatible would cause a compilation error in the generated code.

The third is the only option that provides IntelliSense for properties of the `@Model` property (the HTML helper `model => model.X` case) or (hidden) lambda parameter when using tag helpers (without a leading `@`).

**Comment by dougbu** [comment]
Separately this feature (any of the above options) sounds very general. Users can create properties in any view, not just razor pages. Is the idea to introduce it for razor pages and expand it to be available in views later?

**Comment by DamianEdwards** [comment]
@dougbu I just want HTML helpers and Tag Helpers to work "automatically". **This might just be a limitation of the current prototype**, but the meta-point is: when on a page, without having to specify `@model`, a user should be able to use generic HTML helpers & model expression based Tag Helpers easily, e.g. `@Html.EditorFor(_ => Customer.FirstName)`, `<input asp-for="@Customer.FirstName" />`. If this is already the case, then awesome, but we should ensure the prototype can do it too so we can validate how it feels.

**Comment by DamianEdwards** [comment]
Fixed
